apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minimal-app.fullname" . }}-db
spec:
  storageClassName: {{ .Values.pg.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pg.size }}
