apiVersion: v1
kind: Service
metadata:
  name: {{ include "minimal-app.fullname" . }}-db
  labels:
    {{- include "minimal-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 5432
      targetPort: psql
      protocol: TCP
      name: psql
  selector:
    {{- include "minimal-app.selectorLabelsDB" . | nindent 4 }}
